language: generic
branches:
  only:
    - master
cache:
  directories:
    - vendor
env:
  DEV_REGISTRY=quay.io
services:
  - docker
sudo: required
install:
  - make bootstrap
script:
  - make test build docker-build
