apiVersion: v1
kind: Pod
metadata:
  name: repo_name
  labels:
    heritage: deis
    version: 2.0.0-alpha
spec:
  restartPolicy: Never
  containers:
    - name: deis-slugbuilder
      imagePullPolicy: IfNotPresent
      image: quay.io/deis/slugbuilder:2.0.0-alpha
      env:
        - name: TAR_URL
          value: tar-url
        - name : put_url
          value: puturl
      volumeMounts:
        - name: minio-user
          mountPath: /var/run/secrets/object/store
          readOnly: true
  volumes:
    - name: minio-user
      secret:
        secretName: minio-user
